### PR TITLE
Updated for use in SMF2.1

### PR DESCRIPTION
**Pull request by Bopske**
Here you go, it is all hooks.

There are two language files: english and dutch.
I dit not touch the 1.1 and 2.0 parts, just added the 2.1 stuff so it installs.

Note: I have added some text strings and also used slightly different names for the database settings compared to 1.1 and 2.0...

### CODE REVIEW

**Comment by Flavio93Zena** [comment]
@Bopske  This is mega cool, BUT, on some files (and I can't understand the criteria here), it fails with undefined index (general one, without a variable) at line 165 on the Recent_top.php file. Upon inspecting the browser console, the images that don't load try to load like so: "https://domain.com/post/arrow.png", whereas it should be loading like so "https://domain.com/totallyatestforum/Themes/NameX_v1.0.5/images/post/arrow.png"
All the other ones do work with the correct path, been trying to figure out what is going on but haven't managed to do so, I might be missing something somewhere. Any ideas? Thanks!

**Comment by Bopske** [comment]
No clue what issue that is: the code work prefectly on my site...

**Comment by Flavio93Zena** [comment]
And I can just confirm it doesn't work for all images instead... Some work and some don't, the ones that were converted from gif to png don't work at all in particular.
Changing line 165 from:
`'icon_url' => $settings[$context['icon_sources'][$row['first_icon']]] . '/post/' . $row['first_icon'] . '.png',`
to:
`'icon_url' => $settings['theme_url'] . '/images/post/' . $row['first_icon'] . '.png',`
seems to have fixed the issue for all images and removed the weird redirect.

I can't understand why it happens, at all. The images that don't work are all custom ones but they're alongside the default ones and also present in the default theme. I even enabled the default theme image check in message icon settings, not a factor either.

**Comment by live627** [comment]
@Bopske I now have time and the motivation for this. I'll be pushing my own commits to this/your branch to make this more similar to the existing mod. Okay by you?

**Comment by Bopske** [comment]
> @Bopske I now have time and the motivation for this. I'll be pushing my own commits to this/your branch to make this more similar to the existing mod. Okay by you?

Of course, I contributed my work, as far as I am involved, it is up to you to bring it forward...

**Comment by Bopske** [comment]
> And I can just confirm it doesn't work for all images instead... Some work and some don't, the ones that were converted from gif to png don't work at all in particular. Changing line 165 from: `'icon_url' => $settings[$context['icon_sources'][$row['first_icon']]] . '/post/' . $row['first_icon'] . '.png',` to: `'icon_url' => $settings['theme_url'] . '/images/post/' . $row['first_icon'] . '.png',` seems to have fixed the issue for all images and removed the weird redirect.
> 
> I can't understand why it happens, at all. The images that don't work are all custom ones but they're alongside the default ones and also present in the default theme. I even enabled the default theme image check in message icon settings, not a factor either.

I think I see the issue: the current code only works for SMF default icons, not for icons you have added manually. I do not have any custom topic icons. The code determine the address from $context['stable_icons'] (in line 29), since the custom ones are not in the they do not get the correct url

**Comment by Bopske** [comment]
Ok, just added a fix for the issue with custom post icons. Try the new Recent_top.php code: that should fix it

**Comment by Flavio93Zena** [comment]
I see you added the check, whereas my approach was more brutal :P 

It does indeed work as well without errors, thank you!

**Comment by Bopske** [comment]
IMO it is better to follow the approach that SMF code does. With this code also the functionality of checking theme vs default theme works as standard

**Comment by jsqx** [comment]
Hello. How do I change the position of the Timeline button? I would like to put it before Members, actually I have a Gallery button here, so I would like to put the Timeline button before the Gallery button.

**Comment by live627** [comment]
finally got around to this today. Might be nice to eventually have some javascript to update relative times.

**Comment by Bopske** [comment]
So will you be merging this?

**Comment by live627** [comment]
Thank you!

**Pull request merged**
